pipeline {
    agent any
    tools {
        maven 'maven3.8.6'
        jdk 'jdk'
    }
    stages {

        stage ('Build') {
            steps {
                bat 'mvn -Dmaven.test.failure.ignore=true install'
            }
            post {
                success {
		    echo "Archiveing the Artifacts"
		    archiveArtifacts artifacts: '**/*.war'	
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
        stage("deploy"){
		 steps{

                	deploy adapters: [tomcat9(credentialsId: '09f18ff8-4ba0-4f88-81be-b7d2ca9401be', path: '', url: 'http://localhost:8090/')], contextPath: null, war: '**/*.war'
           			 }
			}
        stage('Sonarqube') {
            environment {
                scannerHome = tool 'SonarQubeScanner'
            }
            steps {
                withSonarQubeEnv('SonarQubeScanner') {
                    bat 'C:/Users/yusuf.ahamed.k/Downloads/sonar-scanner-cli-4.7.0.2747-windows/sonar-scanner-4.7.0.2747-windows/bin/sonar-scanner.bat -D sonar.projectKey=java-maven-junit-helloworld -D sonar.exclusions=**/src/**/*.java'
                }
            }
        }
        
    }
}
