pipeline {
    agent any
    tools {
        maven 'maven3.8.6'
        jdk 'jdk'
    }
    stages {
        stage('Prepare SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/Kyusuf186/java-maven-junit-helloworld.git'
            }
        }
        stage ('Build') {
            steps {
                bat 'mvn -Dmaven.test.failure.ignore=true install'
            }
           	post{
			success{
			    echo "Archiveing the Artifacts"
			    archiveArtifacts artifacts: "**/target/.war*"
				}
                    }
           }
        stage("deploy"){
				steps{
					deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://localhost:9090/')], contextPath: null, war: '**/*.war'
				}
			}
        stage('Sonarqube') {
            environment {
                scannerHome = tool 'SonarQubeScanner'
            }
            steps {
                withSonarQubeEnv('SonarQubeScanner') {
                    //bat 'C:/Users/yusuf.ahamed.k/Downloads/sonar-scanner-cli-4.7.0.2747-windows/sonar-scanner-4.7.0.2747-windows/bin/sonar-scanner.bat -D sonar.projectKey=java-maven-junit-helloworld -D sonar.exclusions=**/src/**/*.java'
                     bat 'mvn clean verify sonar:sonar -Dsonar.projectKey=java-maven-junit-POC' 

                }
            }
        }
        
    }
}
